export const  authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",
};

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

};

export const categoryConstants = {
    Category_Get_Request:"Category_Get_Request",
    Category_Get_Sucess:"Category_Get_Sucess",
    Category_Get_failure:"Category_Get_failure",
    ADD_NEWCATEGORY_REQUEST:"ADD_NEWCATEGORY_REQUEST",
    ADD_NEWCATEGORY_SUCCESS:"ADD_NEWCATEGORY_SUCCESS",
    ADD_NEWCATEGORY_FAILURE:"ADD_NEWCATEGORY_FAILURE"
};


export const productConstants = {

    GET_PRODUCTS_REQUEST: ' GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS:'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    ADD_NEWPRODUCT_REQUEST:'ADD_NEWPRODUCT_REQUEST',
    ADD_NEWPRODUCT_SUCCESS:'ADD_NEWPRODUCT_SUCCESS:',
    ADD_NEWPRODUCT_FAILURE:'ADD_NEWPRODUCT_FAILURE'

};

export const initialDataConstants = {
    GET_INITIALDATA_REQUEST : 'GET_INITIALDATA_REQUEST',
    GET_INITIALDATA_SUCCESS : 'GET_INITIALDATA_SUCCESS',
    GET_INITIALDATA_FAILURE : 'GET_INITIALDATA_FAILURE',
}